version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    ports:
      - "9876:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
